# Generated by Django 5.0.6 on 2024-08-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_account_experiment_enotebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="totalNotebookCount",
            field=models.CharField(default=0),
        ),
    ]
