# Generated by Django 5.0.6 on 2024-08-08 18:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_account_totalnotebookcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="Profile_Photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="Profile_Photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="enotebook",
            name="notebook_number",
            field=models.CharField(null=True, unique=True),
        ),
    ]
