# Generated by Django 5.0.6 on 2024-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_studentprofile_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enotebook",
            name="notebook_number",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="experiment_number",
            field=models.CharField(),
        ),
    ]
