# Generated by Django 5.0.6 on 2024-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("supervisor", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("uid", models.CharField(max_length=255)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
