# Generated by Django 5.0.6 on 2024-08-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_rename_account_experiment_enotebook_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="experimentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.experiment",
                    ),
                ),
            ],
        ),
    ]
