# Generated by Django 5.0.6 on 2024-08-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "enotebooktool",
            "0002_experimentdata_procedure_experimentdata_result_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="reactiionScheme",
            new_name="reactionScheme",
        ),
    ]
