# Generated by Django 5.0.6 on 2024-08-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enotebooktool", "0003_rename_reactiionscheme_reactionscheme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reactionscheme",
            name="experimentData",
        ),
        migrations.RemoveField(
            model_name="reactiontable",
            name="experimentData",
        ),
        migrations.RemoveField(
            model_name="resulttable",
            name="experimentData",
        ),
        migrations.DeleteModel(
            name="analyticalData",
        ),
        migrations.DeleteModel(
            name="reactionScheme",
        ),
        migrations.DeleteModel(
            name="reactionTable",
        ),
        migrations.DeleteModel(
            name="resultTable",
        ),
    ]
