# Generated by Django 5.0.6 on 2024-08-11 18:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enotebooktool", "0004_remove_reactionscheme_experimentdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="analyticalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experimentData",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enotebooktool.experimentdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reactionScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catalyst", models.CharField(default=" ", null=True)),
                ("solvent", models.CharField(default=" ", null=True)),
                ("equation", models.CharField(default=" ", null=True)),
                (
                    "compound_images",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "experimentData",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enotebooktool.experimentdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reactionTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compound", models.CharField(default=" ", null=True)),
                ("molecular_formula", models.IntegerField(blank=True, null=True)),
                ("molecular_weight", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("moles", models.IntegerField(blank=True, null=True)),
                ("ratio", models.IntegerField(blank=True, null=True)),
                ("density", models.IntegerField(blank=True, null=True)),
                (
                    "experimentData",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enotebooktool.experimentdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="resultTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compound_id", models.CharField(default=" ", null=True)),
                ("compound", models.CharField(default=" ", null=True)),
                ("compound_amount", models.IntegerField(blank=True, null=True)),
                ("compound_yield", models.IntegerField(blank=True, null=True)),
                ("compund_moles", models.IntegerField(blank=True, null=True)),
                ("compound_purity", models.IntegerField(blank=True, null=True)),
                ("remarks", models.CharField(default=" ", null=True)),
                (
                    "experimentData",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enotebooktool.experimentdata",
                    ),
                ),
            ],
        ),
    ]
